steps:
# build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/python-server-automated:$REVISION_ID', '.']
# push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/python-server-automated:$REVISION_ID']
# pull/run
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'gcr.io/$PROJECT_ID/python-server-automated:$REVISION_ID']


# testar isso com gcloud repository, nao funciona com git
# steps:
# - name: 'gcr.io/cloud-builders/gcloud'
#   args: ['app', 'deploy']
